--INSERT DO BANCO DA ATVM NO BANCO DOS ADVOGADOS
INSERT	dbo.PostalCodesAdress (Code,Place,Neighborhood,City,State,StateName,Country,InsertByUser,Date)
SELECT	NUM_CEP, ENDERECO, BAIRRO, CIDADE, ESTADO, NOME_ESTADO, 'Brasil', 0, GETDATE()
FROM	[ATVMDB.CMHFVDCRJ8D4.SA-EAST-1.RDS.AMAZONAWS.COM].ATVM01.dbo.CORREIOS_CEP
WHERE	INSERT_USUARIO = 0
ORDER	BY ESTADO, CIDADE, BAIRRO, ENDERECO